apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rollingupdate-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rollingupdate-deployment
    spec:
      containers:
        - name: rollingupdatedemo
          image: myregistry.com/rollingupdatedemo:1
          ports:
            - containerPort: 80