apiVersion: v1
kind: ReplicationController
metadata:
  name: rollingupdate-controller
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: rollingupdate-controller
    spec:
      containers:
        - name: rollingupdatedemo
          image: myregistry.com/rollingupdatedemo:1
          ports:
            - containerPort: 80