apiVersion: v1
kind: Pod
metadata:
  name: port-pod
spec:
  hostNetwork: true
  containers:
    - name: port-pod
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP