apiVersion: v1
kind: Endpoints
metadata:
  name: redis-service
subsets:
  - addresses:
    - ip: 172.18.101.2
    ports:
      - port: 7777
  - addresses:
    - ip: 172.18.101.2
    ports:
        - port: 7778