apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: busybox
      command:
        - sleep
        - "3600"
      envFrom:
        - secretRef:
            name: test-secret
      env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password
      volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true
  volumes:
    - name: data
      secret:
        secretName: test-secret