apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - /bin/bash
        - -c
        - env
      envFrom:
        - configMapRef:
            name: env-configmap
