apiVersion: v1
kind: Pod
metadata:
  name: memory-pod
spec:
  containers:
    - name: memory-pod
      image: vish/stress
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      args:
        - -mem-total
        - 150Mi
        - -mem-alloc-size
        - 10Mi
        - -mem-alloc-sleep
        - 1s